import { type Locale } from "@/lib/types";

const PUBLIC_COPY = {
  de: {
    meta: {
      siteTitle: "Swiss Dental Industry",
      siteDescription: "Verband der Schweizer Dentalindustrie",
      associationTitle: "Der Verband (SVDI) — Swiss Dental Industry",
      associationDescription: "Informationen zum Verband der Schweizer Dentalindustrie (SVDI).",
      membersTitle: "Mitglieder — Swiss Dental Industry",
      membersDescription: "Alle Mitglieder des Verbands der Schweizer Dentalindustrie.",
      newsTitle: "News — Swiss Dental Industry",
      newsDescription: "Aktuelle News und wichtige Termine der Swiss Dental Industry im Überblick.",
      contactTitle: "Kontakt — Swiss Dental Industry",
      contactDescription: "Kontakt und Geschäftsstelle des Verbands der Schweizer Dentalindustrie.",
      joinTitle: "Mitglied werden — Swiss Dental Industry",
      joinDescription: "Mitgliedschaft beim Verband der Schweizer Dentalindustrie beantragen.",
      imprintTitle: "Impressum — Swiss Dental Industry",
      imprintDescription: "Impressum und Kontaktangaben von Swiss Dental Industry.",
      privacyTitle: "Datenschutz — Swiss Dental Industry",
      privacyDescription: "Datenschutzhinweise von Swiss Dental Industry.",
    },
    header: {
      nav: [
        { href: "/#about", label: "Über uns" },
        { href: "/members", label: "Mitglieder" },
        { href: "/news", label: "News" },
        { href: "/contact", label: "Kontakt" },
      ],
      join: "Kontaktieren Sie uns",
      menu: "Menü",
    },
    footer: {
      cols: [
        {
          heading: "Verband",
          links: [
            { label: "Über uns", href: "/about" },
            { label: "Der Vorstand", href: "/contact#vorstand" },
            { label: "News & Termine", href: "/news" },
            { label: "Kontakt", href: "/contact" },
          ],
        },
        {
          heading: "Mitglieder",
          links: [
            { label: "Mitglied werden", href: "/join" },
            { label: "Alle Mitglieder", href: "/members" },
            { label: "Vorteile", href: "/#vorteile" },
          ],
        },
        {
          heading: "Service",
          links: [
            { label: "Presse", href: "/contact#medien" },
            { label: "Impressum", href: "/legal-notice" },
            { label: "Datenschutz", href: "/privacy" },
          ],
        },
      ],
      address:
        "The Association of the Swiss Dental Industry (ASDI / SVDI). Moosstrasse 2, CH-3073 Gümligen - Bern.",
      copyright: "© 2026 Swiss Dental Industry · SVDI",
      tagline: "GÜMLIGEN · BERN · SWITZERLAND SWISS MADE",
    },
    common: {
      news: "News",
      noMembers: "Aktuell sind keine Mitglieder veröffentlicht.",
      noNews: "Aktuell sind keine News veröffentlicht.",
    },
    home: {
      introEyebrow: "Verband der Schweizer Dentalindustrie",
      titleA: "Schweizer Präzision.",
      titleAccent: "Weltweit",
      titleB: "im Einsatz.",
      intro:
        "Wir vertreten die führenden Dentalunternehmen der Schweiz - Hersteller, die mit Präzision, Verlässlichkeit und Innovation den globalen Standard der modernen Zahnmedizin prägen.",
      primaryCta: "Kontaktieren Sie uns",
      secondaryCta: "Die Mitglieder entdecken",
      aboutEyebrow: "Swiss Dental Industry",
      aboutTitle: "Die Schweizer Dentalindustrie",
      aboutText:
        "Die Schweiz geniesst einen gefestigten Ruf für Spitzenleistungen in Präzisionsmechanik, Pharma und akademischer Forschung. In diesem aussergewöhnlichen Umfeld aus Kompetenz und Innovation hat sich die Schweizer Dentalindustrie im letzten Jahrhundert zu einer der weltweit anerkanntesten entwickelt.",
      aboutFacts: [
        "Über 90% der Schweizer Dentalproduktion wird weltweit exportiert",
        "Die Schweiz nimmt eine führende Position in der globalen Medizintechnik ein",
      ],
      expertiseEyebrow: "Unsere Kompetenz",
      expertiseTitle: "Unsere Expertise im Dienst der Fachleute.",
      expertiseLead:
        "Eine gemeinsame Leidenschaft für die Präzisionsindustrie und für die Herausforderungen der Mundgesundheit treibt uns an, aussergewöhnliche Produkte zu entwickeln – täglich gefertigt in bester Schweizer Tradition, um den Bedürfnissen der Zahnärztinnen und Zahnärzte weltweit gerecht zu werden.",
      expertise: [
        {
          n: "01",
          t: "Aussergewöhnliche Produkte",
          d: "In bester Schweizer Tradition gefertigt, um den Ansprüchen und Erwartungen der Praktiker weltweit gerecht zu werden.",
        },
        {
          n: "02",
          t: "Nähe zu den Anwendern",
          d: "Konstante Nähe zu den Anwendern unserer Produkte hält unsere Arbeit im Alltag der Praxis verankert.",
        },
        {
          n: "03",
          t: "Forschung & Messen",
          d: "Enge Hochschulkooperationen und regelmässige Präsenz an Dentalmessen bringen die neuesten Schweizer Innovationen ins Feld.",
        },
      ],
      associationEyebrow: "Der Verband (SVDI)",
      associationTitle: "Wo der Verband heute steht.",
      associationText:
        "Vor bald 70 Jahren gegründet, versammelt unser Verband die Schweizer Dentalhersteller rund um gemeinsame Werte – Präzision, Verlässlichkeit, Innovation und Tradition. Die Qualität unseres Austauschs stärkt den Zusammenhalt der Branche: Grossunternehmen und KMU setzen sich gemeinsam dafür ein, die Identität der Schweizer Dentalindustrie im In- und Ausland zu verteidigen und zu fördern.",
      associationFacts: [
        ["1956", "gegründet"],
        ["__MEMBER_COUNT__", "Mitgliedsfirmen"],
        ["172", "Exportländer"],
        ["FIDE", "Gründungsmitglied"],
      ],
      associationCta: "Mitglied werden",
      membersEyebrow: "Die Mitglieder",
      membersTitle: "Hersteller mit Weltruf.",
      membersCta: "Alle Mitglieder ansehen →",
      newsTitle: "News & Wichtige Termine",
      moreNews: "Weitere News anzeigen",
      lessNews: "Weniger News anzeigen",
      allNews: "Alle News ansehen →",
      joinTitle: "Werden Sie Teil der Schweizer Dentalindustrie.",
      joinText:
        "Eine Mitgliedschaft verbindet Ihr Unternehmen mit dem führenden Netzwerk der Branche - gemeinsame Standards, internationale Sichtbarkeit und eine starke Stimme gegenüber Politik und Markt.",
      joinCta: "Mitglied werden",
    },
    association: {
      eyebrow: "Der Verband",
      title: "Der Verband (SVDI)",
      intro:
        "Dank unseres vor über 60 Jahren gegründeten Verbandes versammeln sich zahlreiche Schweizer Dentalhersteller regelmäßig um unsere gemeinsamen Werte: Präzision, Verlässlichkeit, Innovation und Tradition.",
      facts: [
        "Der Verband wurde 1956 gegründet",
        "Er zählt 30 Mitgliedsgesellschaften, das entspricht über 5.000 Schweizer Arbeitsplätzen.",
        "Er ist ein Gründungsmitglied des Verbandes der Europäischen Dentalindustrie (FIDE)",
      ],
      paragraphs: [
        "Das hohe Niveau des Austauschs, der bei diesen Begegnungen stattfindet, ermöglicht die Verstärkung des Zusammenhalts unserer Branche. Grosse Firmen und mittelgrosse sowie kleine Unternehmen arbeiten zusammen, um gemeinsam die Identität der Schweizer Dentalindustrie hierzulande und ausserhalb zu verteidigen und zu bewerben.",
        "Unsere gemeinsame Leidenschaft für Qualitätsindustrie und die Herausforderungen im Zusammenhang mit Mund- und Zahngesundheit treibt uns an, aussergewöhnliche Produkte zu entwickeln. Unsere Mitglieder arbeiten täglich in bester Schweizer Tradition daran, alle Ansprüche und Bedürfnisse der Praktiker zu befriedigen.",
      ],
      commitments: [
        "Nähe zu den Benutzern schweizerischer Erzeugnisse",
        "Zahlreiche Zusammenarbeiten mit Universitäten weltweit",
        "Regelmässige Anwesenheit bei Dentalveranstaltungen und -messen, um die neuesten Schweizer Dentalinnovationen vorzustellen.",
      ],
      imageAlt: "Messestand der Schweizer Dentalindustrie",
      cardEyebrow: "SVDI",
      cardTitle: "Gemeinsame Werte, gemeinsamer Auftritt.",
      cardText:
        "Der SVDI bringt Unternehmen der Schweizer Dentalindustrie zusammen und stärkt ihren Austausch, ihre Sichtbarkeit und ihre gemeinsame Stimme im In- und Ausland.",
      membersCta: "Mitglieder ansehen",
      joinCta: "Mitglied werden",
    },
    members: {
      eyebrow: "Die Mitglieder",
      title: "Alle Mitgliedsfirmen auf einen Blick.",
      intro:
        "Hier sind alle aktiven Mitglieder des Verbands in einer gemeinsamen Übersicht aufgelistet. Ein Klick auf das jeweilige Feld führt zum Profil mit Beschreibung, Kontaktangaben und Standort.",
      activeLabel: "aktive Mitgliedsfirmen",
      badge: "Logo-Tabelle",
      close: "Schliessen",
      openProfile: "Profil öffnen",
      viewProfile: "Profil ansehen",
      fallbackOrg: "Swiss Dental Industry",
    },
    memberDetail: {
      eyebrow: "Mitglied",
      openWebsite: "Website öffnen",
      allMembers: "Alle Mitglieder",
      descriptionEyebrow: "Beschreibung",
      contactEyebrow: "Kontakt",
      canton: "Kanton",
      noContact: "Kontaktangaben sind aktuell nicht veröffentlicht.",
      profileEyebrow: "Profil",
      status: "Status",
      activeMember: "Aktives Mitglied",
      memberSince: "Mitglied seit",
      language: "Sprache",
      noMap: "Für dieses Mitglied ist noch kein Kartenstandort hinterlegt.",
      googleMaps: "Auf Google Maps →",
      addressFallback: "Swiss Dental Industry",
    },
    newsPage: {
      eyebrow: "News",
      title: "Alle News und wichtigen Termine auf einen Blick.",
      intro:
        "Hier finden Sie sämtliche veröffentlichten Meldungen der Swiss Dental Industry in einer scrollbaren Übersicht.",
    },
    newsDetail: {
      eyebrow: "News",
      moreSoon: "Weitere Informationen folgen.",
      contact: "Kontakt aufnehmen",
      back: "Zur News-Übersicht",
    },
    contact: {
      eyebrow: "Kontakt",
      title: "Sprechen wir miteinander.",
      intro:
        "Die Geschäftsstelle des Verbands der Schweizer Dentalindustrie steht Ihnen für Fragen zur Mitgliedschaft, zur Branche oder zu Medienanfragen zur Verfügung.",
      formEyebrow: "Nachricht senden",
      officeEyebrow: "Geschäftsstelle",
      officeCountry: "Schweiz",
      boardEyebrow: "Vorstand & Organisation",
      boardText:
        "Der Vorstand des SVDI setzt sich aus Vertretenden der Mitgliedsfirmen zusammen. Anfragen zur Zusammensetzung des Vorstands oder zu spezifischen Ressorts richten Sie bitte an die Geschäftsstelle.",
      mediaEyebrow: "Medien & Presse",
      mediaText:
        "Für Medienanfragen, Statements oder Hintergrundgespräche zur Schweizer Dentalindustrie wenden Sie sich an die Geschäftsstelle. Wir antworten in der Regel innerhalb von zwei Arbeitstagen.",
    },
    contactForm: {
      name: "Name *",
      company: "Firma",
      email: "E-Mail *",
      phone: "Telefon",
      subject: "Betreff",
      message: "Nachricht *",
      sending: "Wird gesendet...",
      submit: "Nachricht senden",
      success: "Danke. Ihre Nachricht wurde übermittelt.",
      error: "Kontaktanfrage fehlgeschlagen.",
    },
    join: {
      eyebrow: "Mitglied werden",
      title: "Werden Sie Teil der Schweizer Dentalindustrie.",
      intro:
        "Senden Sie uns Ihre Angaben. Der Antrag wird im Admin-Portal unter Applications gespeichert und die Geschäftsstelle wird per E-Mail informiert.",
      processEyebrow: "Ablauf",
      steps: [
        {
          title: "1. Antrag senden",
          body: "Die wichtigsten Unternehmensdaten landen direkt im Admin-Portal.",
        },
        {
          title: "2. Prüfung",
          body: "Die Geschäftsstelle meldet sich zur Mitgliedschaft und zu offenen Fragen.",
        },
        {
          title: "3. Publikation",
          body: "Nach Freigabe kann Ihr Unternehmen als Mitglied auf der Website erscheinen.",
        },
      ],
    },
    membershipForm: {
      companySection: "Firma",
      contactSection: "Kontaktperson",
      company: "Firmenname *",
      employees: "Mitarbeiterzahl",
      contactLastName: "Nachname *",
      contactFirstName: "Vorname *",
      contactJobTitle: "Funktion",
      contactEmail: "E-Mail *",
      contactPhone: "Telefon",
      contactAddress: "Adresse der Kontaktperson",
      sameAsCompany: "Entspricht der Firmenadresse",
      contact: "Kontaktperson *",
      email: "E-Mail *",
      phone: "Telefon",
      website: "Website",
      address: "Adresse",
      street: "Strasse *",
      streetNumber: "Nummer",
      postalCode: "PLZ *",
      city: "Ort *",
      description: "Kurzbeschreibung *",
      descriptionPlaceholder:
        "Was stellt Ihr Unternehmen her? Welche Rolle hat es in der Dentalindustrie?",
      message: "Nachricht",
      messagePlaceholder: "Fragen, Hinweise oder weitere Angaben zur Mitgliedschaft",
      sending: "Wird gesendet...",
      submit: "Antrag senden",
      success: "Danke. Ihr Antrag wurde gespeichert und an die Geschäftsstelle übermittelt.",
      error: "Antrag fehlgeschlagen.",
      logo: "Firmenlogo",
      logoHint: "PNG, JPG, SVG oder WebP · max. 4 MB. Erscheint auf Ihrer Mitglieder-Karte.",
      logoSelect: "Datei auswählen",
      logoChange: "Logo ändern",
      logoNone: "Keine Datei ausgewählt",
      requiredNote: "Mit * markierte Felder sind Pflicht — sie erscheinen später auf Ihrem öffentlichen Profil.",
      reviewNote: "Ihr Antrag wird von der Geschäftsstelle geprüft. Sie erhalten die Entscheidung per E-Mail; bei Annahme erhalten Sie einen Link, über den Sie Ihre Angaben jederzeit selbst aktualisieren können.",
      missing: "Bitte alle Pflichtfelder ausfüllen.",
      logoTooLarge: "Das Logo ist zu gross (max. 4 MB).",
      logoWrongType: "Bitte ein Bild hochladen (PNG, JPG, SVG oder WebP).",
    },
    imprint: {
      eyebrow: "Impressum",
      content:
        "Verantwortlich für den Inhalt dieser Website ist die Geschäftsstelle des Verbands. Angaben werden mit Sorgfalt gepflegt, eine Haftung für externe Links wird ausgeschlossen.",
    },
    privacy: {
      eyebrow: "Datenschutz",
      title: "Umgang mit Daten",
      paragraphs: [
        "Diese Website verarbeitet personenbezogene Daten, wenn Sie Formulare absenden oder mit der Geschäftsstelle Kontakt aufnehmen. Die Angaben werden zur Bearbeitung Ihrer Anfrage und zur Verwaltung von Mitgliedschaftsanträgen verwendet.",
        "Technisch notwendige Cookies können für Admin-Login, Sprachwahl und Formularfunktionen gesetzt werden. Es werden keine Marketing-Cookies durch diese Website-Komponenten gesetzt.",
        "Für Auskunfts- oder Löschanfragen wenden Sie sich an info@swissdentalindustry.ch.",
      ],
    },
    editForm: {
      eyebrow: "Mitgliederbereich · Self-Service",
      metaTitle: "Firmendaten bearbeiten – Swiss Dental Industry",
      introTitle: "Was ist diese Seite?",
      introWhat: "Über diesen persönlichen Link pflegen Sie die Angaben Ihrer Firma, die auf swissdentalindustry.ch erscheinen. Der Link gehört nur Ihnen — bitte nicht weitergeben.",
      introHow: "Ändern Sie die Felder unten direkt und klicken Sie am Ende auf «Änderungen senden». Die Beschreibung übersetzen wir automatisch in alle vier Sprachen. Was Sie nicht anfassen, bleibt unverändert.",
      introReview: "Ihre Änderungen gehen nicht sofort online: das Sekretariat prüft sie zuerst. Erst nach der Freigabe erscheinen sie auf der Website — Sie werden per E-Mail benachrichtigt.",
      submitLabel: "Änderungen senden",
      invalidTitle: "Link ungültig",
      invalidText: "Dieser Bearbeitungs-Link ist nicht mehr gültig. Bitte wenden Sie sich an Swiss Dental Industry für einen neuen Link.",
      pageTitle: "Firmendaten bearbeiten",
      companyLabel: "Firma",
      publicTabLabel: "Website-Profil",
      internalTabLabel: "Interne Kontaktdaten",
      internalTitle: "Interne Kontaktdaten",
      internalHint:
        "Diese Angaben sind nur für Swiss Dental Industry und erscheinen nicht auf der Website.",
      internalBadge: "Nicht öffentlich",
      pendingWarning: "Sie haben bereits eine offene Änderungsanfrage. Die Felder unten zeigen Ihren zuletzt eingereichten Stand — wenn Sie neue Änderungen senden, ersetzt diese die vorherige Anfrage.",
      logoLabel: "Logo",
      logoHint: "Leer lassen, um das aktuelle Logo zu behalten.",
      descLangLabel: "Sprache Ihrer Beschreibung",
      descLangHint: "Die Sprache wird automatisch aus Ihrem Text erkannt — die Auswahl dient nur als Fallback. Wir übersetzen anschliessend in die anderen Sprachen.",
      descriptionLabel: "Beschreibung",
      addressLabel: "Adresse",
      phoneLabel: "Telefon",
      emailLabel: "E-Mail",
      websiteLabel: "Website",
      submitPending: "Wird gesendet …",
      errors: {
        invalid: "Dieser Link ist nicht mehr gültig.",
        processing: "Beim Verarbeiten ist ein Fehler aufgetreten. Bitte erneut versuchen.",
        save: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
        nochange: "Es wurden keine Änderungen erkannt.",
        duplicate: "Für diese Änderungen gibt es bereits eine offene Anfrage. Bitte warten Sie auf die Prüfung.",
        website: "Bitte geben Sie eine gültige Website-Adresse an (http/https).",
        unknown: "Es ist ein Fehler aufgetreten.",
      },
      doneTitle: "Vielen Dank!",
      doneText: "Ihre Änderungen wurden eingereicht. Wir prüfen sie und Sie werden benachrichtigt, sobald sie live geschaltet sind.",
      doneButton: "Weitere Änderungen vornehmen",
    },
  },
  fr: {
    meta: {
      siteTitle: "Swiss Dental Industry",
      siteDescription: "Association de l'industrie dentaire suisse",
      associationTitle: "L'association (SVDI) — Swiss Dental Industry",
      associationDescription: "Informations sur l'association de l'industrie dentaire suisse (SVDI).",
      membersTitle: "Membres — Swiss Dental Industry",
      membersDescription: "Tous les membres de l'association de l'industrie dentaire suisse.",
      newsTitle: "Actualités — Swiss Dental Industry",
      newsDescription: "Aperçu des actualités et rendez-vous importants de Swiss Dental Industry.",
      contactTitle: "Contact — Swiss Dental Industry",
      contactDescription: "Contact et secrétariat de l'association de l'industrie dentaire suisse.",
      joinTitle: "Devenir membre — Swiss Dental Industry",
      joinDescription: "Demander une adhésion à l'association de l'industrie dentaire suisse.",
      imprintTitle: "Mentions légales — Swiss Dental Industry",
      imprintDescription: "Mentions légales et coordonnées de Swiss Dental Industry.",
      privacyTitle: "Protection des données — Swiss Dental Industry",
      privacyDescription: "Informations sur la protection des données de Swiss Dental Industry.",
    },
    header: {
      nav: [
        { href: "/#about", label: "À propos" },
        { href: "/members", label: "Membres" },
        { href: "/news", label: "Actualités" },
        { href: "/contact", label: "Contact" },
      ],
      join: "Contactez-nous",
      menu: "Menu",
    },
    footer: {
      cols: [
        {
          heading: "Association",
          links: [
            { label: "À propos", href: "/about" },
            { label: "Le comité", href: "/contact#vorstand" },
            { label: "Actualités & rendez-vous", href: "/news" },
            { label: "Contact", href: "/contact" },
          ],
        },
        {
          heading: "Membres",
          links: [
            { label: "Devenir membre", href: "/join" },
            { label: "Tous les membres", href: "/members" },
            { label: "Avantages", href: "/#vorteile" },
          ],
        },
        {
          heading: "Service",
          links: [
            { label: "Presse", href: "/contact#medien" },
            { label: "Mentions légales", href: "/legal-notice" },
            { label: "Protection des données", href: "/privacy" },
          ],
        },
      ],
      address:
        "The Association of the Swiss Dental Industry (ASDI / SVDI). Moosstrasse 2, CH-3073 Gümligen - Bern.",
      copyright: "© 2026 Swiss Dental Industry · SVDI",
      tagline: "GÜMLIGEN · BERNE · SUISSE SWISS MADE",
    },
    common: {
      news: "Actualités",
      noMembers: "Aucun membre n'est actuellement publié.",
      noNews: "Aucune actualité n'est actuellement publiée.",
    },
    home: {
      introEyebrow: "Association de l'industrie dentaire suisse",
      titleA: "La précision suisse.",
      titleAccent: "Dans le monde entier",
      titleB: "à l'œuvre.",
      intro:
        "Nous représentons les principales entreprises dentaires de Suisse, des fabricants qui façonnent le standard mondial de la dentisterie moderne par leur précision, leur fiabilité et leur innovation.",
      primaryCta: "Contactez-nous",
      secondaryCta: "Découvrir les membres",
      aboutEyebrow: "Swiss Dental Industry",
      aboutTitle: "L'industrie dentaire suisse",
      aboutText:
        "La Suisse jouit d'une réputation d'excellence solidement établie en mécanique de précision, en pharmaceutique et dans le domaine académique. C'est dans ce contexte exceptionnel de compétence et d'innovation que l'industrie dentaire suisse s'est développée au siècle dernier pour devenir l'une des plus reconnues au monde.",
      aboutFacts: [
        "Plus de 90% de la production dentaire suisse est exportée dans le monde entier",
        "La Suisse occupe une position de leader dans la technologie médicale mondiale",
      ],
      expertiseEyebrow: "Notre savoir-faire",
      expertiseTitle: "Notre expertise au service des professionnels.",
      expertiseLead:
        "Une passion commune pour l'industrie de précision et pour les défis liés à la santé bucco-dentaire nous pousse à développer des produits exceptionnels – fabriqués chaque jour dans la plus pure tradition suisse pour répondre aux besoins des praticiens du monde entier.",
      expertise: [
        {
          n: "01",
          t: "Produits exceptionnels",
          d: "Fabriqués dans la plus pure tradition suisse pour répondre aux besoins et aux attentes des praticiens du monde entier.",
        },
        {
          n: "02",
          t: "Proximité avec les utilisateurs",
          d: "Une proximité constante avec les utilisateurs de nos produits ancre notre travail dans la pratique quotidienne.",
        },
        {
          n: "03",
          t: "Recherche & salons",
          d: "De solides collaborations académiques et une présence régulière dans les salons dentaires présentent les dernières innovations suisses.",
        },
      ],
      associationEyebrow: "L'association (ASDI)",
      associationTitle: "Où en est l'association aujourd'hui.",
      associationText:
        "Fondée il y a près de 70 ans, notre association rassemble les fabricants dentaires suisses autour de valeurs communes – précision, fiabilité, innovation et tradition. La qualité de nos échanges renforce la cohésion de la branche : grandes entreprises et PME œuvrent ensemble pour défendre et promouvoir l'identité de l'industrie dentaire suisse en Suisse et à l'étranger.",
      associationFacts: [
        ["1956", "fondée"],
        ["__MEMBER_COUNT__", "entreprises membres"],
        ["172", "pays d'exportation"],
        ["FIDE", "membre fondateur"],
      ],
      associationCta: "Devenir membre",
      membersEyebrow: "Les membres",
      membersTitle: "Des fabricants de réputation mondiale.",
      membersCta: "Voir tous les membres →",
      newsTitle: "Actualités & rendez-vous importants",
      moreNews: "Afficher plus d'actualités",
      lessNews: "Afficher moins d'actualités",
      allNews: "Voir toutes les actualités →",
      joinTitle: "Rejoignez l'industrie dentaire suisse.",
      joinText:
        "Une adhésion relie votre entreprise au principal réseau du secteur: standards communs, visibilité internationale et voix forte auprès des autorités et du marché.",
      joinCta: "Devenir membre",
    },
    association: {
      eyebrow: "L'association",
      title: "L'association (SVDI)",
      intro:
        "Grâce à notre association fondée il y a plus de 60 ans, de nombreux fabricants dentaires suisses se réunissent régulièrement autour de nos valeurs communes: précision, fiabilité, innovation et tradition.",
      facts: [
        "L'association a été fondée en 1956",
        "Elle compte 30 sociétés membres, soit plus de 5 000 emplois en Suisse.",
        "Elle est membre fondateur de la Fédération de l'industrie dentaire européenne (FIDE)",
      ],
      paragraphs: [
        "La qualité élevée des échanges qui ont lieu lors de ces rencontres renforce la cohésion de notre secteur. De grandes entreprises ainsi que des sociétés moyennes et petites collaborent pour défendre et promouvoir ensemble l'identité de l'industrie dentaire suisse en Suisse et à l'étranger.",
        "Notre passion commune pour une industrie de qualité et pour les défis liés à la santé bucco-dentaire nous pousse à développer des produits exceptionnels. Nos membres travaillent chaque jour dans la meilleure tradition suisse afin de répondre à toutes les attentes et à tous les besoins des praticiens.",
      ],
      commitments: [
        "Proximité avec les utilisateurs des produits suisses",
        "Nombreuses collaborations avec des universités dans le monde entier",
        "Présence régulière lors de manifestations et salons dentaires afin de présenter les dernières innovations dentaires suisses.",
      ],
      imageAlt: "Stand de l'industrie dentaire suisse",
      cardEyebrow: "SVDI",
      cardTitle: "Des valeurs communes, une présence commune.",
      cardText:
        "La SVDI réunit les entreprises de l'industrie dentaire suisse et renforce leurs échanges, leur visibilité et leur voix commune en Suisse et à l'étranger.",
      membersCta: "Voir les membres",
      joinCta: "Devenir membre",
    },
    members: {
      eyebrow: "Les membres",
      title: "Toutes les entreprises membres en un coup d'œil.",
      intro:
        "Tous les membres actifs de l'association sont listés ici dans une vue d'ensemble commune. Un clic sur chaque carte mène au profil avec description, coordonnées et localisation.",
      activeLabel: "entreprises membres actives",
      badge: "Tableau des logos",
      close: "Fermer",
      openProfile: "Ouvrir le profil",
      viewProfile: "Voir le profil",
      fallbackOrg: "Swiss Dental Industry",
    },
    memberDetail: {
      eyebrow: "Membre",
      openWebsite: "Ouvrir le site web",
      allMembers: "Tous les membres",
      descriptionEyebrow: "Description",
      contactEyebrow: "Contact",
      canton: "Canton",
      noContact: "Les coordonnées ne sont actuellement pas publiées.",
      profileEyebrow: "Profil",
      status: "Statut",
      activeMember: "Membre actif",
      memberSince: "Membre depuis",
      language: "Langue",
      noMap: "Aucun emplacement cartographique n'est encore enregistré pour ce membre.",
      googleMaps: "Voir sur Google Maps →",
      addressFallback: "Swiss Dental Industry",
    },
    newsPage: {
      eyebrow: "Actualités",
      title: "Toutes les actualités et rendez-vous importants en un coup d'œil.",
      intro:
        "Vous trouverez ici toutes les publications de Swiss Dental Industry dans une vue d'ensemble défilante.",
    },
    newsDetail: {
      eyebrow: "Actualités",
      moreSoon: "Plus d'informations suivront.",
      contact: "Prendre contact",
      back: "Retour aux actualités",
    },
    contact: {
      eyebrow: "Contact",
      title: "Parlons ensemble.",
      intro:
        "Le secrétariat de l'association de l'industrie dentaire suisse se tient à votre disposition pour toute question sur l'adhésion, le secteur ou les demandes des médias.",
      formEyebrow: "Envoyer un message",
      officeEyebrow: "Secrétariat",
      officeCountry: "Suisse",
      boardEyebrow: "Comité & organisation",
      boardText:
        "Le comité de la SVDI se compose de représentants des entreprises membres. Pour toute question sur sa composition ou sur des ressorts spécifiques, veuillez vous adresser au secrétariat.",
      mediaEyebrow: "Médias & presse",
      mediaText:
        "Pour les demandes des médias, déclarations ou entretiens de fond sur l'industrie dentaire suisse, veuillez contacter le secrétariat. Nous répondons en règle générale sous deux jours ouvrables.",
    },
    contactForm: {
      name: "Nom *",
      company: "Entreprise",
      email: "E-mail *",
      phone: "Téléphone",
      subject: "Sujet",
      message: "Message *",
      sending: "Envoi en cours...",
      submit: "Envoyer le message",
      success: "Merci. Votre message a bien été transmis.",
      error: "L'envoi de la demande de contact a échoué.",
    },
    join: {
      eyebrow: "Devenir membre",
      title: "Rejoignez l'industrie dentaire suisse.",
      intro:
        "Envoyez-nous vos informations. La demande sera enregistrée dans le portail admin sous Applications et le secrétariat sera informé par e-mail.",
      processEyebrow: "Déroulement",
      steps: [
        { title: "1. Envoyer la demande", body: "Les principales données de l'entreprise arrivent directement dans le portail admin." },
        { title: "2. Examen", body: "Le secrétariat vous recontacte au sujet de l'adhésion et des éventuelles questions ouvertes." },
        { title: "3. Publication", body: "Après validation, votre entreprise peut apparaître comme membre sur le site." },
      ],
    },
    membershipForm: {
      companySection: "Entreprise",
      contactSection: "Personne de contact",
      company: "Raison sociale *",
      employees: "Nombre de collaborateurs",
      contactLastName: "Nom *",
      contactFirstName: "Prénom *",
      contactJobTitle: "Fonction",
      contactEmail: "E-mail *",
      contactPhone: "Téléphone",
      contactAddress: "Adresse de la personne de contact",
      sameAsCompany: "Identique à l'adresse de l'entreprise",
      contact: "Personne de contact *",
      email: "E-mail *",
      phone: "Téléphone",
      website: "Site web",
      address: "Adresse",
      street: "Rue *",
      streetNumber: "Numéro",
      postalCode: "NPA *",
      city: "Localité *",
      description: "Brève description *",
      descriptionPlaceholder: "Que fabrique votre entreprise ? Quel est son rôle dans l'industrie dentaire ?",
      message: "Message",
      messagePlaceholder: "Questions, remarques ou autres informations concernant l'adhésion",
      sending: "Envoi en cours...",
      submit: "Envoyer la demande",
      success: "Merci. Votre demande a été enregistrée et transmise au secrétariat.",
      error: "La demande a échoué.",
      logo: "Logo de l'entreprise",
      logoHint: "PNG, JPG, SVG ou WebP · max. 4 Mo. Apparaît sur votre fiche membre.",
      logoSelect: "Choisir un fichier",
      logoChange: "Changer le logo",
      logoNone: "Aucun fichier sélectionné",
      requiredNote: "Les champs marqués d'un * sont obligatoires — ils figureront sur votre profil public.",
      reviewNote: "Votre demande est examinée par le secrétariat. Vous recevrez la décision par e-mail; en cas d'acceptation, un lien vous permettra de mettre à jour vos données à tout moment.",
      missing: "Veuillez remplir tous les champs obligatoires.",
      logoTooLarge: "Le logo est trop volumineux (max. 4 Mo).",
      logoWrongType: "Veuillez télécharger une image (PNG, JPG, SVG ou WebP).",
    },
    imprint: {
      eyebrow: "Mentions légales",
      content:
        "Le secrétariat de l'association est responsable du contenu de ce site. Les informations sont entretenues avec soin, toute responsabilité pour les liens externes est exclue.",
    },
    privacy: {
      eyebrow: "Protection des données",
      title: "Traitement des données",
      paragraphs: [
        "Ce site traite des données personnelles lorsque vous envoyez des formulaires ou contactez le secrétariat. Les informations sont utilisées pour traiter votre demande et gérer les demandes d'adhésion.",
        "Des cookies techniquement nécessaires peuvent être utilisés pour la connexion admin, le choix de la langue et les fonctions des formulaires. Aucun cookie marketing n'est déposé par ces composants du site.",
        "Pour toute demande d'accès ou de suppression, veuillez contacter info@swissdentalindustry.ch.",
      ],
    },
    editForm: {
      eyebrow: "Espace membres · Self-service",
      metaTitle: "Modifier les données de l'entreprise – Swiss Dental Industry",
      introTitle: "À quoi sert cette page ?",
      introWhat: "Ce lien personnel vous permet de gérer les informations de votre entreprise telles qu'elles apparaissent sur swissdentalindustry.ch. Ce lien n'appartient qu'à vous — merci de ne pas le transmettre.",
      introHow: "Modifiez directement les champs ci-dessous, puis cliquez sur « Envoyer les modifications ». Nous traduisons automatiquement la description dans les quatre langues. Ce que vous ne touchez pas reste inchangé.",
      introReview: "Vos modifications ne sont pas publiées immédiatement : le secrétariat les vérifie d'abord. Elles n'apparaissent sur le site qu'après validation — vous serez informé par e-mail.",
      submitLabel: "Envoyer les modifications",
      invalidTitle: "Lien invalide",
      invalidText: "Ce lien de modification n'est plus valide. Veuillez contacter Swiss Dental Industry pour obtenir un nouveau lien.",
      pageTitle: "Modifier les données de l'entreprise",
      companyLabel: "Entreprise",
      publicTabLabel: "Profil du site web",
      internalTabLabel: "Données de contact internes",
      internalTitle: "Données de contact internes",
      internalHint:
        "Ces informations sont réservées à Swiss Dental Industry et n'apparaissent pas sur le site web.",
      internalBadge: "Non public",
      pendingWarning: "Vous avez déjà une demande de modification en attente. Les champs ci-dessous affichent votre dernier état soumis — si vous envoyez de nouvelles modifications, elles remplaceront la demande précédente.",
      logoLabel: "Logo",
      logoHint: "Laisser vide pour conserver le logo actuel.",
      descLangLabel: "Langue de votre description",
      descLangHint: "La langue est détectée automatiquement à partir de votre texte — la sélection sert uniquement de repli. Nous traduisons ensuite vers les autres langues.",
      descriptionLabel: "Description",
      addressLabel: "Adresse",
      phoneLabel: "Téléphone",
      emailLabel: "E-mail",
      websiteLabel: "Site web",
      submitPending: "Envoi en cours …",
      errors: {
        invalid: "Ce lien n'est plus valide.",
        processing: "Une erreur s'est produite. Veuillez réessayer.",
        save: "Échec de l'enregistrement. Veuillez réessayer.",
        nochange: "Aucune modification détectée.",
        duplicate: "Une demande ouverte existe déjà pour ces modifications. Veuillez attendre la vérification.",
        website: "Veuillez indiquer une adresse de site web valide (http/https).",
        unknown: "Une erreur s'est produite.",
      },
      doneTitle: "Merci beaucoup !",
      doneText: "Vos modifications ont été soumises. Nous les examinerons et vous serez notifié dès leur mise en ligne.",
      doneButton: "Apporter d'autres modifications",
    },
  },
  it: {
    meta: {
      siteTitle: "Swiss Dental Industry",
      siteDescription: "Associazione dell'industria dentale svizzera",
      associationTitle: "L'associazione (SVDI) — Swiss Dental Industry",
      associationDescription: "Informazioni sull'associazione dell'industria dentale svizzera (SVDI).",
      membersTitle: "Membri — Swiss Dental Industry",
      membersDescription: "Tutti i membri dell'associazione dell'industria dentale svizzera.",
      newsTitle: "News — Swiss Dental Industry",
      newsDescription: "Panoramica delle news e degli appuntamenti importanti di Swiss Dental Industry.",
      contactTitle: "Contatto — Swiss Dental Industry",
      contactDescription: "Contatto e segreteria dell'associazione dell'industria dentale svizzera.",
      joinTitle: "Diventare membro — Swiss Dental Industry",
      joinDescription: "Richiedere l'adesione all'associazione dell'industria dentale svizzera.",
      imprintTitle: "Colophon — Swiss Dental Industry",
      imprintDescription: "Colophon e contatti di Swiss Dental Industry.",
      privacyTitle: "Protezione dei dati — Swiss Dental Industry",
      privacyDescription: "Informazioni sulla protezione dei dati di Swiss Dental Industry.",
    },
    header: {
      nav: [
        { href: "/#about", label: "Chi siamo" },
        { href: "/members", label: "Membri" },
        { href: "/news", label: "News" },
        { href: "/contact", label: "Contatto" },
      ],
      join: "Contattaci",
      menu: "Menu",
    },
    footer: {
      cols: [
        {
          heading: "Associazione",
          links: [
            { label: "Chi siamo", href: "/about" },
            { label: "Il comitato", href: "/contact#vorstand" },
            { label: "News e appuntamenti", href: "/news" },
            { label: "Contatto", href: "/contact" },
          ],
        },
        {
          heading: "Membri",
          links: [
            { label: "Diventare membro", href: "/join" },
            { label: "Tutti i membri", href: "/members" },
            { label: "Vantaggi", href: "/#vorteile" },
          ],
        },
        {
          heading: "Servizio",
          links: [
            { label: "Stampa", href: "/contact#medien" },
            { label: "Colophon", href: "/legal-notice" },
            { label: "Protezione dei dati", href: "/privacy" },
          ],
        },
      ],
      address:
        "The Association of the Swiss Dental Industry (ASDI / SVDI). Moosstrasse 2, CH-3073 Gümligen - Bern.",
      copyright: "© 2026 Swiss Dental Industry · SVDI",
      tagline: "GÜMLIGEN · BERNA · SVIZZERA SWISS MADE",
    },
    common: {
      news: "News",
      noMembers: "Al momento non sono pubblicati membri.",
      noNews: "Al momento non sono pubblicate news.",
    },
    home: {
      introEyebrow: "Associazione dell'industria dentale svizzera",
      titleA: "Precisione svizzera.",
      titleAccent: "Nel mondo",
      titleB: "in azione.",
      intro:
        "Rappresentiamo le principali aziende dentali della Svizzera, produttori che definiscono lo standard globale dell'odontoiatria moderna con precisione, affidabilità e innovazione.",
      primaryCta: "Contattaci",
      secondaryCta: "Scoprire i membri",
      aboutEyebrow: "Swiss Dental Industry",
      aboutTitle: "L'industria dentale svizzera",
      aboutText:
        "La Svizzera gode di una solida reputazione di eccellenza nella meccanica di precisione, nella farmaceutica e nell'ambito accademico. È in questo contesto eccezionale di competenza e innovazione che l'industria dentale svizzera si è sviluppata nell'ultimo secolo fino a diventare una delle più riconosciute al mondo.",
      aboutFacts: [
        "Oltre il 90% della produzione dentale svizzera è esportato in tutto il mondo",
        "La Svizzera occupa una posizione di primo piano nella tecnologia medica globale",
      ],
      expertiseEyebrow: "Le nostre competenze",
      expertiseTitle: "La nostra esperienza al servizio dei professionisti.",
      expertiseLead:
        "Una passione comune per l'industria di precisione e per le sfide legate alla salute orale ci spinge a sviluppare prodotti eccezionali – realizzati ogni giorno nella più pura tradizione svizzera per rispondere alle esigenze dei professionisti dentali di tutto il mondo.",
      expertise: [
        {
          n: "01",
          t: "Prodotti eccezionali",
          d: "Realizzati nella più pura tradizione svizzera per soddisfare le esigenze e le aspettative dei professionisti di tutto il mondo.",
        },
        {
          n: "02",
          t: "Vicinanza agli utilizzatori",
          d: "Una vicinanza costante agli utilizzatori dei nostri prodotti mantiene il nostro lavoro radicato nella pratica quotidiana.",
        },
        {
          n: "03",
          t: "Ricerca & fiere",
          d: "Solide collaborazioni accademiche e una presenza regolare alle fiere dentali presentano le ultime innovazioni svizzere.",
        },
      ],
      associationEyebrow: "L'associazione (ASDI)",
      associationTitle: "A che punto è oggi l'associazione.",
      associationText:
        "Fondata quasi 70 anni fa, la nostra associazione riunisce i produttori dentali svizzeri attorno a valori comuni – precisione, affidabilità, innovazione e tradizione. La qualità dei nostri scambi rafforza la coesione del settore: grandi aziende e PMI collaborano per difendere e promuovere l'identità dell'industria dentale svizzera in patria e all'estero.",
      associationFacts: [
        ["1956", "fondata"],
        ["__MEMBER_COUNT__", "aziende associate"],
        ["172", "paesi di esportazione"],
        ["FIDE", "membro fondatore"],
      ],
      associationCta: "Diventare membro",
      membersEyebrow: "I membri",
      membersTitle: "Produttori di fama mondiale.",
      membersCta: "Vedere tutti i membri →",
      newsTitle: "News e appuntamenti importanti",
      moreNews: "Mostrare altre news",
      lessNews: "Mostrare meno news",
      allNews: "Vedere tutte le news →",
      joinTitle: "Entrate a far parte dell'industria dentale svizzera.",
      joinText:
        "L'adesione collega la vostra azienda alla rete leader del settore: standard comuni, visibilità internazionale e una voce forte verso politica e mercato.",
      joinCta: "Diventare membro",
    },
    association: {
      eyebrow: "L'associazione",
      title: "L'associazione (SVDI)",
      intro:
        "Grazie alla nostra associazione fondata oltre 60 anni fa, numerosi produttori dentali svizzeri si riuniscono regolarmente attorno ai nostri valori comuni: precisione, affidabilità, innovazione e tradizione.",
      facts: [
        "L'associazione è stata fondata nel 1956",
        "Conta 30 società membri, pari a oltre 5.000 posti di lavoro in Svizzera.",
        "È membro fondatore della Federazione dell'industria dentale europea (FIDE)",
      ],
      paragraphs: [
        "L'elevato livello di scambio che si svolge durante questi incontri rafforza la coesione del nostro settore. Grandi aziende, così come imprese medie e piccole, collaborano per difendere e promuovere insieme l'identità dell'industria dentale svizzera in patria e all'estero.",
        "La nostra passione condivisa per un'industria di qualità e per le sfide legate alla salute orale e dentale ci spinge a sviluppare prodotti straordinari. I nostri membri lavorano ogni giorno nella migliore tradizione svizzera per soddisfare tutte le esigenze dei professionisti.",
      ],
      commitments: [
        "Vicinanza agli utilizzatori dei prodotti svizzeri",
        "Numerose collaborazioni con università di tutto il mondo",
        "Presenza regolare a manifestazioni e fiere dentali per presentare le più recenti innovazioni dentali svizzere.",
      ],
      imageAlt: "Stand dell'industria dentale svizzera",
      cardEyebrow: "SVDI",
      cardTitle: "Valori comuni, presenza comune.",
      cardText:
        "La SVDI riunisce le aziende dell'industria dentale svizzera e rafforza il loro scambio, la loro visibilità e la loro voce comune in Svizzera e all'estero.",
      membersCta: "Vedere i membri",
      joinCta: "Diventare membro",
    },
    members: {
      eyebrow: "I membri",
      title: "Tutte le aziende associate a colpo d'occhio.",
      intro:
        "Qui sono elencati tutti i membri attivi dell'associazione in una panoramica comune. Un clic su ogni riquadro porta al profilo con descrizione, contatti e posizione.",
      activeLabel: "aziende associate attive",
      badge: "Tabella loghi",
      close: "Chiudi",
      openProfile: "Aprire il profilo",
      viewProfile: "Vedere il profilo",
      fallbackOrg: "Swiss Dental Industry",
    },
    memberDetail: {
      eyebrow: "Membro",
      openWebsite: "Aprire il sito web",
      allMembers: "Tutti i membri",
      descriptionEyebrow: "Descrizione",
      contactEyebrow: "Contatto",
      canton: "Cantone",
      noContact: "I dati di contatto non sono attualmente pubblicati.",
      profileEyebrow: "Profilo",
      status: "Stato",
      activeMember: "Membro attivo",
      memberSince: "Membro dal",
      language: "Lingua",
      noMap: "Per questo membro non è ancora stata registrata una posizione sulla mappa.",
      googleMaps: "Apri su Google Maps →",
      addressFallback: "Swiss Dental Industry",
    },
    newsPage: {
      eyebrow: "News",
      title: "Tutte le news e gli appuntamenti importanti a colpo d'occhio.",
      intro:
        "Qui trovate tutte le pubblicazioni di Swiss Dental Industry in una panoramica scorrevole.",
    },
    newsDetail: {
      eyebrow: "News",
      moreSoon: "Seguiranno ulteriori informazioni.",
      contact: "Contattaci",
      back: "Torna alle news",
    },
    contact: {
      eyebrow: "Contatto",
      title: "Parliamone.",
      intro:
        "La segreteria dell'associazione dell'industria dentale svizzera è a vostra disposizione per domande su adesione, settore o richieste media.",
      formEyebrow: "Inviare un messaggio",
      officeEyebrow: "Segreteria",
      officeCountry: "Svizzera",
      boardEyebrow: "Comitato & organizzazione",
      boardText:
        "Il comitato della SVDI è composto da rappresentanti delle aziende associate. Per domande sulla composizione del comitato o su specifici ambiti di competenza, rivolgetevi alla segreteria.",
      mediaEyebrow: "Media & stampa",
      mediaText:
        "Per richieste dei media, dichiarazioni o colloqui di approfondimento sull'industria dentale svizzera, contattate la segreteria. Di norma rispondiamo entro due giorni lavorativi.",
    },
    contactForm: {
      name: "Nome *",
      company: "Azienda",
      email: "E-mail *",
      phone: "Telefono",
      subject: "Oggetto",
      message: "Messaggio *",
      sending: "Invio in corso...",
      submit: "Inviare il messaggio",
      success: "Grazie. Il vostro messaggio è stato trasmesso.",
      error: "La richiesta di contatto non è andata a buon fine.",
    },
    join: {
      eyebrow: "Diventare membro",
      title: "Entrate a far parte dell'industria dentale svizzera.",
      intro:
        "Inviateci i vostri dati. La richiesta verrà salvata nel portale admin sotto Applications e la segreteria sarà informata via e-mail.",
      processEyebrow: "Procedura",
      steps: [
        { title: "1. Inviare la richiesta", body: "I principali dati aziendali arrivano direttamente nel portale admin." },
        { title: "2. Verifica", body: "La segreteria vi contatterà in merito all'adesione e ad eventuali questioni aperte." },
        { title: "3. Pubblicazione", body: "Dopo l'approvazione, la vostra azienda potrà comparire come membro sul sito." },
      ],
    },
    membershipForm: {
      companySection: "Azienda",
      contactSection: "Persona di contatto",
      company: "Ragione sociale *",
      employees: "Numero di collaboratori",
      contactLastName: "Cognome *",
      contactFirstName: "Nome *",
      contactJobTitle: "Funzione",
      contactEmail: "E-mail *",
      contactPhone: "Telefono",
      contactAddress: "Indirizzo della persona di contatto",
      sameAsCompany: "Corrisponde all'indirizzo dell'azienda",
      contact: "Persona di contatto *",
      email: "E-mail *",
      phone: "Telefono",
      website: "Sito web",
      address: "Indirizzo",
      street: "Via *",
      streetNumber: "Numero",
      postalCode: "CAP *",
      city: "Località *",
      description: "Breve descrizione *",
      descriptionPlaceholder: "Cosa produce la vostra azienda? Qual è il suo ruolo nell'industria dentale?",
      message: "Messaggio",
      messagePlaceholder: "Domande, note o ulteriori informazioni sull'adesione",
      sending: "Invio in corso...",
      submit: "Inviare la richiesta",
      success: "Grazie. La vostra richiesta è stata salvata e trasmessa alla segreteria.",
      error: "La richiesta non è andata a buon fine.",
      logo: "Logo aziendale",
      logoHint: "PNG, JPG, SVG o WebP · max. 4 MB. Appare sulla vostra scheda membro.",
      logoSelect: "Scegliere un file",
      logoChange: "Cambiare logo",
      logoNone: "Nessun file selezionato",
      requiredNote: "I campi contrassegnati con * sono obbligatori — appariranno sul vostro profilo pubblico.",
      reviewNote: "La vostra richiesta viene esaminata dalla segreteria. Riceverete la decisione via e-mail; in caso di accettazione, un link vi permetterà di aggiornare i vostri dati in qualsiasi momento.",
      missing: "Si prega di compilare tutti i campi obbligatori.",
      logoTooLarge: "Il logo è troppo grande (max. 4 MB).",
      logoWrongType: "Si prega di caricare un'immagine (PNG, JPG, SVG o WebP).",
    },
    imprint: {
      eyebrow: "Colophon",
      content:
        "La segreteria dell'associazione è responsabile del contenuto di questo sito. Le informazioni sono curate con attenzione; è esclusa qualsiasi responsabilità per link esterni.",
    },
    privacy: {
      eyebrow: "Protezione dei dati",
      title: "Gestione dei dati",
      paragraphs: [
        "Questo sito elabora dati personali quando inviate moduli o contattate la segreteria. I dati vengono utilizzati per trattare la vostra richiesta e gestire le domande di adesione.",
        "Cookie tecnicamente necessari possono essere impostati per il login admin, la scelta della lingua e le funzioni dei moduli. Nessun cookie di marketing viene impostato da questi componenti del sito.",
        "Per richieste di accesso o cancellazione rivolgetevi a info@swissdentalindustry.ch.",
      ],
    },
    editForm: {
      eyebrow: "Area soci · Self-service",
      metaTitle: "Modifica i dati aziendali – Swiss Dental Industry",
      introTitle: "Che cos'è questa pagina?",
      introWhat: "Con questo link personale gestisci i dati della tua azienda così come appaiono su swissdentalindustry.ch. Il link appartiene solo a te — non trasmetterlo.",
      introHow: "Modifica direttamente i campi qui sotto e clicca su «Invia modifiche». La descrizione viene tradotta automaticamente nelle quattro lingue. Ciò che non tocchi resta invariato.",
      introReview: "Le modifiche non vanno online subito: il segretariato le verifica prima. Appaiono sul sito solo dopo l'approvazione — riceverai una notifica via e-mail.",
      submitLabel: "Invia modifiche",
      invalidTitle: "Link non valido",
      invalidText: "Questo link di modifica non è più valido. Si prega di contattare Swiss Dental Industry per un nuovo link.",
      pageTitle: "Modifica i dati aziendali",
      companyLabel: "Azienda",
      publicTabLabel: "Profilo sito web",
      internalTabLabel: "Dati di contatto interni",
      internalTitle: "Dati di contatto interni",
      internalHint:
        "Queste informazioni sono riservate a Swiss Dental Industry e non compaiono sul sito web.",
      internalBadge: "Non pubblico",
      pendingWarning: "Avete già una richiesta di modifica in sospeso. I campi sottostanti mostrano l'ultimo stato inviato — se inviate nuove modifiche, sostituiranno la richiesta precedente.",
      logoLabel: "Logo",
      logoHint: "Lasciare vuoto per mantenere il logo attuale.",
      descLangLabel: "Lingua della vostra descrizione",
      descLangHint: "La lingua viene rilevata automaticamente dal vostro testo — la selezione serve solo come riserva. Traduciamo poi nelle altre lingue.",
      descriptionLabel: "Descrizione",
      addressLabel: "Indirizzo",
      phoneLabel: "Telefono",
      emailLabel: "E-mail",
      websiteLabel: "Sito web",
      submitPending: "Invio in corso …",
      errors: {
        invalid: "Questo link non è più valido.",
        processing: "Si è verificato un errore. Si prega di riprovare.",
        save: "Salvataggio fallito. Si prega di riprovare.",
        nochange: "Nessuna modifica rilevata.",
        duplicate: "Esiste già una richiesta aperta per queste modifiche. Si prega di attendere la verifica.",
        website: "Inserisca un indirizzo web valido (http/https).",
        unknown: "Si è verificato un errore.",
      },
      doneTitle: "Grazie mille!",
      doneText: "Le vostre modifiche sono state inviate. Le esamineremo e sarete avvisati non appena saranno pubblicate.",
      doneButton: "Apportare ulteriori modifiche",
    },
  },
  en: {
    meta: {
      siteTitle: "Swiss Dental Industry",
      siteDescription: "Association of the Swiss dental industry",
      associationTitle: "The Association (SVDI) — Swiss Dental Industry",
      associationDescription: "Information about the association of the Swiss dental industry (SVDI).",
      membersTitle: "Members — Swiss Dental Industry",
      membersDescription: "All members of the association of the Swiss dental industry.",
      newsTitle: "News — Swiss Dental Industry",
      newsDescription: "Overview of current news and important dates from Swiss Dental Industry.",
      contactTitle: "Contact — Swiss Dental Industry",
      contactDescription: "Contact and secretariat of the association of the Swiss dental industry.",
      joinTitle: "Become a Member — Swiss Dental Industry",
      joinDescription: "Apply for membership in the association of the Swiss dental industry.",
      imprintTitle: "Legal Notice — Swiss Dental Industry",
      imprintDescription: "Legal notice and contact details for Swiss Dental Industry.",
      privacyTitle: "Privacy — Swiss Dental Industry",
      privacyDescription: "Privacy information for Swiss Dental Industry.",
    },
    header: {
      nav: [
        { href: "/#about", label: "About" },
        { href: "/members", label: "Members" },
        { href: "/news", label: "News" },
        { href: "/contact", label: "Contact" },
      ],
      join: "Contact us",
      menu: "Menu",
    },
    footer: {
      cols: [
        {
          heading: "Association",
          links: [
            { label: "About us", href: "/about" },
            { label: "The board", href: "/contact#vorstand" },
            { label: "News & dates", href: "/news" },
            { label: "Contact", href: "/contact" },
          ],
        },
        {
          heading: "Members",
          links: [
            { label: "Become a member", href: "/join" },
            { label: "All members", href: "/members" },
            { label: "Benefits", href: "/#vorteile" },
          ],
        },
        {
          heading: "Service",
          links: [
            { label: "Press", href: "/contact#medien" },
            { label: "Legal notice", href: "/legal-notice" },
            { label: "Privacy", href: "/privacy" },
          ],
        },
      ],
      address:
        "The Association of the Swiss Dental Industry (ASDI / SVDI). Moosstrasse 2, CH-3073 Gümligen - Bern.",
      copyright: "© 2026 Swiss Dental Industry · SVDI",
      tagline: "GÜMLIGEN · BERN · SWITZERLAND SWISS MADE",
    },
    common: {
      news: "News",
      noMembers: "There are currently no published members.",
      noNews: "There is currently no published news.",
    },
    home: {
      introEyebrow: "Association of the Swiss Dental Industry",
      titleA: "Swiss precision.",
      titleAccent: "Worldwide",
      titleB: "in action.",
      intro:
        "We represent Switzerland's leading dental companies - manufacturers shaping the global standard of modern dentistry through precision, reliability, and innovation.",
      primaryCta: "Contact us",
      secondaryCta: "Discover the Members",
      aboutEyebrow: "Swiss Dental Industry",
      aboutTitle: "The Swiss Dental Industry",
      aboutText:
        "Switzerland's reputation for excellence in precision mechanics, pharmaceuticals and academic research is firmly established. In this exceptional context of competence and innovation, the Swiss dental industry grew over the last century into one of the most recognised in the world.",
      aboutFacts: [
        "More than 90% of Swiss dental production is exported worldwide",
        "Switzerland holds a leading position in global medical technology",
      ],
      expertiseEyebrow: "Our expertise",
      expertiseTitle: "Our expertise at the service of professionals.",
      expertiseLead:
        "A shared passion for the precision industry and for the challenges of oral health drives us to develop exceptional products – manufactured daily in the purest Swiss tradition to meet the needs of dental practitioners worldwide.",
      expertise: [
        {
          n: "01",
          t: "Exceptional products",
          d: "Crafted in the purest Swiss tradition to meet the needs and expectations of practitioners everywhere.",
        },
        {
          n: "02",
          t: "Close to users",
          d: "Constant proximity with the users of our products keeps our work grounded in everyday practice.",
        },
        {
          n: "03",
          t: "Research & fairs",
          d: "Strong academic collaborations and a regular presence at dental events showcase the latest Swiss innovations.",
        },
      ],
      associationEyebrow: "Our Association (ASDI)",
      associationTitle: "Where the association stands today.",
      associationText:
        "Founded nearly 70 years ago, our association brings Swiss dental manufacturers together around shared values – precision, reliability, innovation and tradition. The quality of our exchanges strengthens the cohesion of the sector: large corporations and SMEs work side by side to defend and promote the identity of the Swiss dental industry at home and abroad.",
      associationFacts: [
        ["1956", "founded"],
        ["__MEMBER_COUNT__", "member companies"],
        ["172", "export countries"],
        ["FIDE", "founding member"],
      ],
      associationCta: "Become a member",
      membersEyebrow: "The Members",
      membersTitle: "Manufacturers with a global reputation.",
      membersCta: "View all members →",
      newsTitle: "News & Important Dates",
      moreNews: "Show more news",
      lessNews: "Show fewer news items",
      allNews: "View all news →",
      joinTitle: "Become part of the Swiss dental industry.",
      joinText:
        "Membership connects your company with the industry's leading network - shared standards, international visibility, and a strong voice toward policymakers and the market.",
      joinCta: "Become a Member",
    },
    association: {
      eyebrow: "The Association",
      title: "The Association (SVDI)",
      intro:
        "Thanks to our association, founded more than 60 years ago, numerous Swiss dental manufacturers regularly come together around our shared values: precision, reliability, innovation, and tradition.",
      facts: [
        "The association was founded in 1956",
        "It counts 30 member companies, representing more than 5,000 jobs in Switzerland.",
        "It is a founding member of the Federation of the European Dental Industry (FIDE)",
      ],
      paragraphs: [
        "The high level of exchange that takes place during these meetings strengthens the cohesion of our industry. Large companies as well as medium-sized and smaller businesses work together to defend and promote the identity of the Swiss dental industry at home and abroad.",
        "Our shared passion for quality industry and the challenges related to oral and dental health drives us to develop exceptional products. Our members work every day in the best Swiss tradition to meet all the expectations and needs of practitioners.",
      ],
      commitments: [
        "Closeness to the users of Swiss products",
        "Numerous collaborations with universities worldwide",
        "Regular presence at dental events and trade fairs to present the latest Swiss dental innovations.",
      ],
      imageAlt: "Swiss dental industry exhibition stand",
      cardEyebrow: "SVDI",
      cardTitle: "Shared values, shared presence.",
      cardText:
        "SVDI brings together companies from the Swiss dental industry and strengthens their exchange, visibility, and shared voice at home and abroad.",
      membersCta: "View members",
      joinCta: "Become a Member",
    },
    members: {
      eyebrow: "The Members",
      title: "All member companies at a glance.",
      intro:
        "All active members of the association are listed here in one shared overview. Clicking a card opens the profile with description, contact details, and location.",
      activeLabel: "active member companies",
      badge: "Logo grid",
      close: "Close",
      openProfile: "Open profile",
      viewProfile: "View profile",
      fallbackOrg: "Swiss Dental Industry",
    },
    memberDetail: {
      eyebrow: "Member",
      openWebsite: "Open website",
      allMembers: "All members",
      descriptionEyebrow: "Description",
      contactEyebrow: "Contact",
      canton: "Canton",
      noContact: "Contact details are currently not published.",
      profileEyebrow: "Profile",
      status: "Status",
      activeMember: "Active member",
      memberSince: "Member since",
      language: "Language",
      noMap: "No map location has been stored for this member yet.",
      googleMaps: "Open in Google Maps →",
      addressFallback: "Swiss Dental Industry",
    },
    newsPage: {
      eyebrow: "News",
      title: "All news and important dates at a glance.",
      intro:
        "Here you can find all published Swiss Dental Industry updates in a scrollable overview.",
    },
    newsDetail: {
      eyebrow: "News",
      moreSoon: "More information will follow.",
      contact: "Get in touch",
      back: "Back to news overview",
    },
    contact: {
      eyebrow: "Contact",
      title: "Let's talk.",
      intro:
        "The secretariat of the association of the Swiss dental industry is available for questions about membership, the sector, or media inquiries.",
      formEyebrow: "Send a message",
      officeEyebrow: "Secretariat",
      officeCountry: "Switzerland",
      boardEyebrow: "Board & organisation",
      boardText:
        "The SVDI board is composed of representatives from member companies. Please direct questions about the board's composition or specific areas of responsibility to the secretariat.",
      mediaEyebrow: "Media & press",
      mediaText:
        "For media inquiries, statements, or background discussions about the Swiss dental industry, please contact the secretariat. We usually respond within two working days.",
    },
    contactForm: {
      name: "Name *",
      company: "Company",
      email: "Email *",
      phone: "Phone",
      subject: "Subject",
      message: "Message *",
      sending: "Sending...",
      submit: "Send message",
      success: "Thank you. Your message has been sent.",
      error: "Contact request failed.",
    },
    join: {
      eyebrow: "Become a Member",
      title: "Become part of the Swiss dental industry.",
      intro:
        "Send us your details. The application is stored in the admin portal under Applications and the secretariat is notified by email.",
      processEyebrow: "Process",
      steps: [
        { title: "1. Send application", body: "The key company details go directly into the admin portal." },
        { title: "2. Review", body: "The secretariat gets back to you regarding membership and any open questions." },
        { title: "3. Publication", body: "After approval, your company can appear as a member on the website." },
      ],
    },
    membershipForm: {
      companySection: "Company",
      contactSection: "Contact person",
      company: "Company name *",
      employees: "Number of employees",
      contactLastName: "Last name *",
      contactFirstName: "First name *",
      contactJobTitle: "Job title",
      contactEmail: "Email *",
      contactPhone: "Phone",
      contactAddress: "Contact person's address",
      sameAsCompany: "Same as company address",
      contact: "Contact person *",
      email: "Email *",
      phone: "Phone",
      website: "Website",
      address: "Address",
      street: "Street *",
      streetNumber: "Number",
      postalCode: "Postal code *",
      city: "City *",
      description: "Short description *",
      descriptionPlaceholder: "What does your company produce? What role does it play in the dental industry?",
      message: "Message",
      messagePlaceholder: "Questions, notes, or additional information about membership",
      sending: "Sending...",
      submit: "Send application",
      success: "Thank you. Your application has been saved and forwarded to the secretariat.",
      error: "Application failed.",
      logo: "Company logo",
      logoHint: "PNG, JPG, SVG or WebP · max 4 MB. Shown on your member card.",
      logoSelect: "Choose file",
      logoChange: "Change logo",
      logoNone: "No file selected",
      requiredNote: "Fields marked * are required — they appear on your public profile.",
      reviewNote: "Your application is reviewed by the secretariat. You will receive the decision by email; if accepted, you get a link to update your details at any time.",
      missing: "Please fill in all required fields.",
      logoTooLarge: "The logo is too large (max 4 MB).",
      logoWrongType: "Please upload an image (PNG, JPG, SVG or WebP).",
    },
    imprint: {
      eyebrow: "Legal Notice",
      content:
        "The association's secretariat is responsible for the content of this website. Information is maintained with due care; liability for external links is excluded.",
    },
    privacy: {
      eyebrow: "Privacy",
      title: "Handling of data",
      paragraphs: [
        "This website processes personal data when you submit forms or contact the secretariat. The information is used to handle your request and manage membership applications.",
        "Technically necessary cookies may be set for admin login, language selection, and form functions. No marketing cookies are set by these website components.",
        "For access or deletion requests, please contact info@swissdentalindustry.ch.",
      ],
    },
    editForm: {
      eyebrow: "Member area · Self-service",
      metaTitle: "Edit company profile – Swiss Dental Industry",
      introTitle: "What is this page?",
      introWhat: "This personal link lets you maintain the details of your company as they appear on swissdentalindustry.ch. The link is yours alone — please do not pass it on.",
      introHow: "Edit the fields below directly, then click “Send changes”. We translate the description into all four languages automatically. Anything you do not touch stays as it is.",
      introReview: "Your changes do not go online straight away: the secretariat reviews them first. They only appear on the website once approved — you will be notified by email.",
      submitLabel: "Send changes",
      invalidTitle: "Invalid link",
      invalidText: "This edit link is no longer valid. Please contact Swiss Dental Industry for a new link.",
      pageTitle: "Edit company profile",
      companyLabel: "Company",
      publicTabLabel: "Website profile",
      internalTabLabel: "Internal contact data",
      internalTitle: "Internal contact data",
      internalHint:
        "This information is for Swiss Dental Industry only and does not appear on the website.",
      internalBadge: "Not public",
      pendingWarning: "You already have an open change request. The fields below show your last submitted state — if you send new changes, they will replace the previous request.",
      logoLabel: "Logo",
      logoHint: "Leave empty to keep the current logo.",
      descLangLabel: "Language of your description",
      descLangHint: "The language is detected automatically from your text — the selection only serves as a fallback. We then translate into the other languages.",
      descriptionLabel: "Description",
      addressLabel: "Address",
      phoneLabel: "Phone",
      emailLabel: "E-mail",
      websiteLabel: "Website",
      submitPending: "Sending …",
      errors: {
        invalid: "This link is no longer valid.",
        processing: "An error occurred while processing. Please try again.",
        save: "Save failed. Please try again.",
        nochange: "No changes detected.",
        duplicate: "An open request already exists for these changes. Please wait for the review.",
        website: "Please enter a valid website address (http/https).",
        unknown: "An error occurred.",
      },
      doneTitle: "Thank you!",
      doneText: "Your changes have been submitted. We will review them and you will be notified once they go live.",
      doneButton: "Make further changes",
    },
  },
} as const;

export function getPublicCopy(locale: Locale) {
  return PUBLIC_COPY[locale];
}
